---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: bgp-cloud-connector-mirror-set
spec:
  imageDigestMirrors:
    # Mirrors for the FBC v4-22 and v5-0 catalog images
    - source: registry.redhat.io/bgpcc/bgp-cloud-connector-operator-catalog
      mirrors:
        - quay.io/redhat-user-workloads/bgp-cloud-connector-tenant/bgp-cloud-connector-fbc-v4-22/bgp-cloud-connector-fbc-v4-22
        - quay.io/redhat-user-workloads/bgp-cloud-connector-tenant/bgp-cloud-connector-fbc-v5-0/bgp-cloud-connector-fbc-v5-0
    # Mirror for the operator bundle
    - source: registry.redhat.io/bgpcc/bgp-cloud-connector-operator-bundle
      mirrors:
        - quay.io/redhat-user-workloads/bgp-cloud-connector-tenant/bgp-cloud-connector/bgp-cloud-connector-bundle
    # Mirror for the operator image
    - source: registry.redhat.io/bgpcc/bgp-cloud-connector-rhel9-operator
      mirrors:
        - quay.io/redhat-user-workloads/bgp-cloud-connector-tenant/bgp-cloud-connector/bgp-cloud-connector-operator
